import java.io.File;
import java.io.IOException;
import java.sql.Date;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author andon
 */
public class ANDONI extends javax.swing.JFrame {

    /**
     * Creates new form ventana_datos
     */
    public ANDONI() {
        initComponents();
        getContentPane().setBackground(java.awt.Color.BLACK);
        bdatos.setBackground(java.awt.Color.DARK_GRAY);
        bdatos.setForeground(java.awt.Color.WHITE);
        String prueba = "A ver si se actualiza esta bullshit";
        String otra_prueba = "Para actualizar desde el navegador";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        bdatos = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bdatos.setLabel("Enséñame esos datos");
        bdatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(137, Short.MAX_VALUE)
                                .addComponent(bdatos, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(bdatos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void bdatosActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            File directorio = new File("C:\\Users\\andon\\Documents\\NetBeansProjects\\Dia1\\src\\archivos");
            File archivo_3 = new File("C:\\Users\\andon\\Documents\\NetBeansProjects\\Dia1\\src\\archivos\\holi");
            File[] archivos = directorio.listFiles();

            archivo_3.createNewFile();
            for (File nombre : archivos) {
                JOptionPane.showMessageDialog(rootPane, "Nombre: " + nombre.getName() + "\n tamaño: " + nombre.length() + "\n Fecha de última modificacion: " + new Date(nombre.lastModified()));

                if (nombre.canWrite()) {
                    JOptionPane.showMessageDialog(rootPane, nombre.getName() + " Tiene permisos");

                }
                else{
                    JOptionPane.showMessageDialog(rootPane, nombre.getName() + " No tiene permisos");
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ANDONI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ANDONI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ANDONI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ANDONI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ANDONI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private java.awt.Button bdatos;
    // End of variables declaration
}

